### ISSUE TITLE
Gnu-grep can print lines of context before/after the match

### ISSUE THREAD

**Issue by ofnuts** [beyondgrep/website#118]
From the man page:

```
   Context Line Control
       -A NUM, --after-context=NUM
              Print  NUM lines of trailing context after matching lines.  Places a line containing
              a group separator (--) between  contiguous  groups  of  matches.   With  the  -o  or
              --only-matching option, this has no effect and a warning is given.

       -B NUM, --before-context=NUM
              Print  NUM lines of leading context before matching lines.  Places a line containing
              a group separator (--) between  contiguous  groups  of  matches.   With  the  -o  or
              --only-matching option, this has no effect and a warning is given.

       -C NUM, -NUM, --context=NUM
              Print  NUM lines of output context.  Places a line containing a group separator (--)
              between contiguous groups of matches.  With the -o or --only-matching  option,  this
              has no effect and a warning is given.
```

**Comment by n1vux** [comment]
Do we have any idea when between gnu-grep 2.21 and 3.4 this was introduced? 

Thought crosses my mind that we may need to use not just a boolean check mark but `POSIX` or a version number for features of gnu-grep, as as with so many commandline tools it has grown so since the Unix SysVr2 temporary reunification of Bell+BSD. I'd need a time series of Gnu-Grep man pages to figure  that out for all the args.

**Comment by ofnuts** [comment]
Already there in a grep 2.20 found in a CentOs 7.4 docker image (RHEL/CentOS are great resources for software archeologists).

**Comment by ofnuts** [comment]
Digging deeper, a CentOS5 docker image has grep 2.5.1 with a copyright from 2001. The `-A`, `-B`, and `-C` options are already there.

**Comment by petdance** [comment]
There's no disputing context as a feature of grep.  It's just a mistake on the chart.

**Comment by petdance** [comment]
Looks like there's a bug in the parsing of features.json.  It's noted correctly in there:

```
            {
                "what": "Print lines of context after matches",
                "how": {
                    "ack,ag,git,gnu,rg": "-A --after",
                    "freebsd,netbsd,osx": "-A --after-context"
                }
            },
```

So something is rendering it incorrectly.

**Comment by petdance** [comment]
This has been fixed.  Thanks for pointing it out.
