### ISSUE TITLE
feature comparison: ag and long lines

### ISSUE THREAD

**Issue by bazzargh** [beyondgrep/website#75]
The chart mentions the '‑‑print‑long‑lines' ag flag for 'Print matches on very long lines' - which was documented but never implemented - but does not mention the '-W NUM' flag for 'Limit length of output lines', which does work but is underdocumented (it's in the --help output but not on the man page). See
https://github.com/ggreer/the_silver_searcher/pull/720

**Comment by petdance** [comment]
Thanks.  Updated in aa102c2 and published.
