### ISSUE TITLE
rg can search compressed (gzip, bzip2, lzma, xz) files in 0.8.0

### ISSUE THREAD

**Issue by awwaiid** [beyondgrep/website#88]
From https://github.com/BurntSushi/ripgrep/blob/master/CHANGELOG.md#080-2018-02-11

> 0.8.0 (2018-02-11)
> 
> This is a new minor version releae of ripgrep that satisfies several popular feature requests (config files, search compressed files, true colors)...

...

> FEATURE #539: Search gzip, bzip2, lzma or xz files when given -z/--search-zip flag.

**Comment by n1vux** [comment]
Interesting, the _possibility_ of doing just that (via a variant file iterator) was one of the motivations for **Ack2**'s "plugin" architecture ... which alas slowed down the "normal" case sufficiently and yet never actually used that it was jettisoned for **Ack3**. 

(As a usecase, grep-ing through compressed files and archives is likely more useful for Bibliographic / Forensic / Litigation-support work than Ack's primary usecase of a coder making sense of a legacy codebase (where code i haven't looked at for 6 months is likely already "legacy" to me :-/ ). There are cases where i might have 20 tarballs un-extracted and want to know how many of them include a token or pattern-match, but usually I'm working with one of them expanded.)

If we don't already have **"Labels"** named for sections of the website (other tools, grid, faq, ...) we should do so, so we can tag this as applying to the feature comparison **grid**.

**Comment by petdance** [comment]
I'll add a note to the grid.

**Comment by petdance** [comment]
Updated.  Thanks.
