### ISSUE TITLE
feature comparison: ag uses threads

### ISSUE THREAD

**Issue by lapo-luchini** [beyondgrep/website#90]
You could basically duplicate [line 144](https://github.com/beyondgrep/website/blob/10a8ab6b7b05e47e361171299b837f7439156fbf/features.json#L114) `s/rg/ag`.
Proof: [official README](https://github.com/ggreer/the_silver_searcher/blob/1b06a9fd8d9ad0aaf235b4a752e605dfd4bb7ced/README.md).

**Comment by petdance** [comment]
Updated. Thank you.
