### ISSUE TITLE
ripgrep --ignore-file is misclassified

### ISSUE THREAD

**Issue by xordspar0** [beyondgrep/website#95]
The feature comparison table of classifies ripgrep's `--ignore-file` option next to grep's `--exclude` under "Ignore files/directories matching". In fact, `--ignore-file` doesn't specify files that should be excluded from the search, but rather a file that contains patterns for ignoring files. It can be used to specify an alternative file to `.gitignore`.

From the man page:

    --ignore-file PATH ...
        Specifies a path to one or more .gitignore format rules files. These
        patterns are applied after the patterns found in .gitignore and .ignore
        are applied and are matched relative to the current working directory.
        Multiple additional ignore files can be specified by using the
        --ignore-file flag several times. When specifying multiple ignore files,
        earlier files have lower precedence than later files.

**Comment by petdance** [comment]
Nice catch. Thank you.
