### ISSUE TITLE
corrections for ripgrep

### ISSUE THREAD

**Issue by BurntSushi** [beyondgrep/website#97]
Hiya @petdance! Thanks so much for maintaining the feature comparison table. I'd like to just drop a note with some additions/corrections for ripgrep, since a fair bit has been added I think since this table was created.

I'm just going to go down the list of things in the same order that the table is in and point out changes for ripgrep specifically.

* Regular expressions - ripgrep now has a `-P` flag, like grep, which enables Perl-compatible regexes (via PCRE2).
* Search filetype by pattern match on filename - The `-g/--glob` does this. (As far as I know, the same is true for _all_ of the tools in the table, except for perhaps `git grep`. But `ag` and `grep` certainly support it.)
* Configuration file - ripgrep has one now, by setting the `RIPGREP_CONFIG_PATH` env var.
* Deterministic output - Should be `--sort path` now. (`--sort-files` still works, but is deprecated.)
* Match patterns across newlines - The `-U/--multiline` flag does this.
* Search in gzip files - Works via the `-z/--search-zip` flag.
* Match patterns across newlines - The `-U/--multiline` flag does this. (Duplicate table entry?)
* Use Perl (or Perl-compatible) regular expressions - The `-P/--pcre2` flag does this.
* Print the byte offset within the file before each line - The `-b/--byte-offset` flag does this.
* Print stats (files scanned, time taken, etc.) - The `--stats` flag does this.
* Group together all matches in a file - The `--heading` flag does this.
* Flush output on every line - The `--line-buffered` flag does this.
* List searchable files that match a pattern - The `-g/--glob` flag does this.
* Sort the found files lexically - Should be `--sort path` now. (`--sort-files` still works, but is deprecated.)
* Limit search to filenames matching a pattern - The `-g/--glob` flag does this.
* Recurse into subdirectories - ripgrep does this by default, but `--max-depth` can be used to control the recursion depth.
* Recurse into subdirectories, following symlinks - The `-L/--follow` flag does this.
* No descending into subdirectories - Using `--max-depth 1` will achieve this.
* Add/remove directory from list of ignored dirs - I think you can just say that the `-g/--glob` does this, since it applies to directories as well.
* Add filter for ignoring files - The `-g/--glob` flag does this.
* Include only files of types that ack recognizes - Using `-t all` will do this. (This should probably say, "Include only files of recognized types." :P)
* Don't follow links to other devices - The `--one-file-system` flag does this.
* Search all text files - Using `-t txt` should do this.
* Skip rules found in VCS ignore files (.gitignore, .hgignore, etc) - The `--no-ignore-vcs` flag should do this.
* Print all lines, whether matching or not - The `--passthru` flag does this.
* Dump information on which options are loaded - The `--debug` flag does this (among other things).
* Ignore environment variables and global configuration files - The `--no-config` flag does this.

I might have misunderstood some of the entries in the table, especially where I repeated myself. But I figured I'd just throw everything out there that made sense to me and leave it up to your judgment. :-)

Thanks!

**Comment by stdedos** [comment]
> Regular expressions - ripgrep now has a -P flag, like grep, which enables Perl-compatible regexes (via PCRE2).

-P/--pcre2 (use PCRE2 always) or --auto-hybrid-regex (use PCRE2 only if needed)

**Comment by petdance** [comment]
@stdedos @BurntSushi If either of you want to go modify the JSON and submit me a PR, that would be swell.  I'd really like to make these updates but it's not a top priority right now.
